server:
  port: 9000

spring:
  application:
    name: auth
  cloud:
    consul:
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 10s
        health-check-critical-timeout: 20s
        instance-id: ${spring.application.name}
        service-name: auth
        prefer-ip-address: true
      config:
        fail-fast: false # if not in "prod" profile, do not force to use Spring Cloud Config
        format: yaml
        profile-separator: '-'
        watch:
          enabled: false
        enabled: false

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?useUnicode=yes&characterEncoding=UTF-8
    username: admin
    password: admin
    hikari:
      data-source-properties:
        stringtype: unspecified
        useUnicode: true
        characterEncoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update

config:
  oauth2:
    clientId: talk2amareswaran
    clientSecret: talk2amareswaran@123
  jwt:
    secret-key: password
    alias: oauth2

redis:
  host: localhost
  port: 6379
  expired-time: 86400 # 24 hour