version: "3"

services: 
    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: oauth2
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin

    consul:
        image: consul:1.9.4
        ports:
            - 8300:8300
            - 8500:8500
            - 8600:8600
        command: consul agent -dev -ui -client 0.0.0.0 -log-level=INFO

    redis:
        image: redis
        container_name: cache
        ports:
            - 6379:6379